-- DB BACKUP: BOM Manager / EngineFlow-PM --
-- Generated at: 2026-04-07T04:48:25.728Z --

-- Table: project_subsections --
-- (Empty table: project_subsections)

-- Table: suppliers --
INSERT INTO "suppliers" ("id", "name", "contact_person", "email", "phone", "address", "payment_terms", "notes", "created_date", "updated_date") VALUES ('7', 'Cubix Automation', 'cubixautomation', 'gaurav@cubixautomation.net', ': 9881642742\9226549819', 'Office No 101, Ramya Apartment, Near Tathawade Garden,,
Saraswat Bank Lane, Karve Nagar, Pune ,
Pune, Maharashtra, IND, 411052', '', '', '2026-04-02T11:12:06.774Z', NULL);
INSERT INTO "suppliers" ("id", "name", "contact_person", "email", "phone", "address", "payment_terms", "notes", "created_date", "updated_date") VALUES ('9', 'Rexel', 'AKSHAY', 'akshay@rexel.com', '+91 97634 17820', '', '', '', '2026-04-04T11:28:21.072Z', NULL);
INSERT INTO "suppliers" ("id", "name", "contact_person", "email", "phone", "address", "payment_terms", "notes", "created_date", "updated_date") VALUES ('10', 'Pioneer Technology', 'Tushar Ghone', 'tushar@pioneertechnology.in', '+91-8888830107', 'Survey No. 452/1/1, Saidatta Reality, 
Alankapuram Road,near godown chowk,
Moshi,Pune 412105
', '', '', '2026-04-06T06:49:10.220Z', NULL);
INSERT INTO "suppliers" ("id", "name", "contact_person", "email", "phone", "address", "payment_terms", "notes", "created_date", "updated_date") VALUES ('11', 'Vashi Integrated Solutions Limited', 'Shubhangi Kamble', 'shubhangi.kamble@vashiisl.com', '86557 80247', 'VISL - Branch-Pune Taluka Khed Shed No.1Gat No. 82, Gaikwad Warehouse, At Post - Karuli, IN 91 7045453551 Pune
Pune 410501', 'Advance', '', '2026-04-06T06:58:31.979Z', NULL);
INSERT INTO "suppliers" ("id", "name", "contact_person", "email", "phone", "address", "payment_terms", "notes", "created_date", "updated_date") VALUES ('12', 'SEW', '', '', '', '', '', '', '2026-04-06T07:29:35.827Z', NULL);
INSERT INTO "suppliers" ("id", "name", "contact_person", "email", "phone", "address", "payment_terms", "notes", "created_date", "updated_date") VALUES ('13', 'Padmavati Engineering Solutions', '', '', '', 'Sector No-10, Plot No 221,
MIDC, Bhosari Pune,
Pune, Maharashtra, IND, 411039
GSTIN : 27BGKPR4311J1Z6', '', '', '2026-04-06T11:01:51.647Z', NULL);

-- Table: projects --
INSERT INTO "projects" ("id", "project_name", "project_number", "customer", "description", "status", "start_date", "target_completion_date", "actual_completion_date", "mechanical_design_status", "ee_design_status", "pneumatic_design_status", "po_release_status", "part_arrival_status", "machine_build_status", "created_date", "updated_date") VALUES ('7', 'MG LM6 CAMERA CALIBRATION', '70021', 'MG', 'A	Standalone Type Vehicle Center System:
 	o        Main support frame which includes supporting fixture for sub-assemblies，
	machine cover plates
 	o        Front axle positioning (rollers)
 	o        Rear axle positioning (rollers)
 	o        Centering unit (front wheels)
 	o        Centering unit (rear wheels)
 	o        Set of side guide rollers
b	Camera Calibration Floor Target
 	o        Targets for calibration pattern plates fixed on floor
 	o        Guided rollers (F/R)
 	o        360 calibration setup software
c	Camera Calibration 30 TV Target
 	o        SUPPLY OF 30 TV 32 INCH , Mounting as per Pattern position data
 	o        CMM calibration to verify TV mounting at site
 	o        TV mounting structure 
d	Master Gauge 
 	o        Master gauge for Machine Calibration 
', 'design', '2026-03-31T18:30:00.000Z', '2026-04-29T18:30:00.000Z', NULL, 'in_progress', 'not_started', 'not_started', 'not_started', 'not_started', 'not_started', '2026-04-02T11:07:56.245Z', NULL);
INSERT INTO "projects" ("id", "project_name", "project_number", "customer", "description", "status", "start_date", "target_completion_date", "actual_completion_date", "mechanical_design_status", "ee_design_status", "pneumatic_design_status", "po_release_status", "part_arrival_status", "machine_build_status", "created_date", "updated_date") VALUES ('9', 'MG LM6- REAR GANTRY', '70020', 'MG', 'Front Radar Plate Change as per LM6 requirement
o        New 700 mm * 700 mm Radar reflection plate as per Requirement in Bosch Protocol
o        Software modification of Front radar Calibration for LM6
Rear Corner Radar gantry Addition
o        New Rear gantry with control integrated to current ACC PLC
o        Two Corner reflector integrated to rear gantry with Y and Z movement
o  Each Corner reflector with Absorbent Board 
o Modification of Existing Master Gauge for Rear gantry Calibration
o CMM of Master Gauge at site During installation
o Rear radar calibration target setup software
 
', 'design', NULL, NULL, NULL, 'in_progress', 'in_progress', 'in_progress', 'not_started', 'not_started', 'not_started', '2026-04-04T06:50:47.135Z', NULL);

-- Table: mechanical_manufacture --
INSERT INTO "mechanical_manufacture" ("id", "part_number", "beperp_part_no", "description", "supplier_id", "base_price", "currency", "discount_percent", "stock_quantity", "min_stock_level", "order_qty", "received_qty", "lead_time", "total_amount", "total_stock", "specifications", "manufacturer", "manufacturer_part_number", "material", "finish", "weight", "datasheet_url", "image_path", "cad_file_url", "pdm_file_path", "vendor_part_number", "po_number", "pdf_path", "pdf2_path", "pdf3_path", "created_date", "updated_date") VALUES ('11', 'MM-9101587', '9101587', 'ROLLER WASHER-SS304', NULL, '170.00', 'INR', '0.00', 0, 0, 0, 0, NULL, '0.00', 0, NULL, 'Padmavati Engineering Solutions', NULL, 'SS304', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-04-06T11:35:03.050Z', NULL);
INSERT INTO "mechanical_manufacture" ("id", "part_number", "beperp_part_no", "description", "supplier_id", "base_price", "currency", "discount_percent", "stock_quantity", "min_stock_level", "order_qty", "received_qty", "lead_time", "total_amount", "total_stock", "specifications", "manufacturer", "manufacturer_part_number", "material", "finish", "weight", "datasheet_url", "image_path", "cad_file_url", "pdm_file_path", "vendor_part_number", "po_number", "pdf_path", "pdf2_path", "pdf3_path", "created_date", "updated_date") VALUES ('12', 'MM-9101588', '9101588', 'U-RING-SS304', NULL, '295.00', 'INR', '0.00', 0, 0, 0, 0, NULL, '0.00', 0, NULL, 'Padmavati Engineering Solutions', NULL, 'SS304', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-04-06T11:35:04.156Z', NULL);
INSERT INTO "mechanical_manufacture" ("id", "part_number", "beperp_part_no", "description", "supplier_id", "base_price", "currency", "discount_percent", "stock_quantity", "min_stock_level", "order_qty", "received_qty", "lead_time", "total_amount", "total_stock", "specifications", "manufacturer", "manufacturer_part_number", "material", "finish", "weight", "datasheet_url", "image_path", "cad_file_url", "pdm_file_path", "vendor_part_number", "po_number", "pdf_path", "pdf2_path", "pdf3_path", "created_date", "updated_date") VALUES ('13', 'MM-9101589', '9101589', 'COLLAR CAP-SS304', NULL, '1100.00', 'INR', '0.00', 0, 0, 0, 0, NULL, '0.00', 0, NULL, 'Padmavati Engineering Solutions', NULL, 'SS304', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-04-06T11:35:05.456Z', NULL);
INSERT INTO "mechanical_manufacture" ("id", "part_number", "beperp_part_no", "description", "supplier_id", "base_price", "currency", "discount_percent", "stock_quantity", "min_stock_level", "order_qty", "received_qty", "lead_time", "total_amount", "total_stock", "specifications", "manufacturer", "manufacturer_part_number", "material", "finish", "weight", "datasheet_url", "image_path", "cad_file_url", "pdm_file_path", "vendor_part_number", "po_number", "pdf_path", "pdf2_path", "pdf3_path", "created_date", "updated_date") VALUES ('5', 'MM-9101581', '9101581', 'ROLLER SHAFT REAR -EN21', '13', '965.00', 'INR', '0.00', 0, 0, 0, 0, NULL, '0.00', 0, NULL, 'Padmavati Engineering Solutions', NULL, 'EN21', NULL, NULL, NULL, 'https://buvzefqfoeyupxsmhgkd.supabase.co/storage/v1/object/public/bom_assets/zn1naq4l4xo-1775478459994.png', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-04-06T11:34:55.058Z', NULL);
INSERT INTO "mechanical_manufacture" ("id", "part_number", "beperp_part_no", "description", "supplier_id", "base_price", "currency", "discount_percent", "stock_quantity", "min_stock_level", "order_qty", "received_qty", "lead_time", "total_amount", "total_stock", "specifications", "manufacturer", "manufacturer_part_number", "material", "finish", "weight", "datasheet_url", "image_path", "cad_file_url", "pdm_file_path", "vendor_part_number", "po_number", "pdf_path", "pdf2_path", "pdf3_path", "created_date", "updated_date") VALUES ('6', 'MM-9101582', '9101582', 'ROLLER REAR-SS304', '13', '3925.00', 'INR', '0.00', 0, 0, 0, 0, NULL, '0.00', 0, NULL, 'Padmavati Engineering Solutions', NULL, 'SS304', NULL, NULL, NULL, 'https://buvzefqfoeyupxsmhgkd.supabase.co/storage/v1/object/public/bom_assets/hedacrohb7f-1775478499063.png', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-04-06T11:34:56.271Z', NULL);
INSERT INTO "mechanical_manufacture" ("id", "part_number", "beperp_part_no", "description", "supplier_id", "base_price", "currency", "discount_percent", "stock_quantity", "min_stock_level", "order_qty", "received_qty", "lead_time", "total_amount", "total_stock", "specifications", "manufacturer", "manufacturer_part_number", "material", "finish", "weight", "datasheet_url", "image_path", "cad_file_url", "pdm_file_path", "vendor_part_number", "po_number", "pdf_path", "pdf2_path", "pdf3_path", "created_date", "updated_date") VALUES ('7', 'MM-9101583', '9101583', 'BIG ROLLER SHAFT FRONT -EN21', '13', '1015.00', 'INR', '0.00', 0, 0, 0, 0, NULL, '0.00', 0, NULL, 'Padmavati Engineering Solutions', NULL, 'EN21', NULL, NULL, NULL, 'https://buvzefqfoeyupxsmhgkd.supabase.co/storage/v1/object/public/bom_assets/eu9lk7rnewh-1775478542025.png', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-04-06T11:34:58.586Z', NULL);
INSERT INTO "mechanical_manufacture" ("id", "part_number", "beperp_part_no", "description", "supplier_id", "base_price", "currency", "discount_percent", "stock_quantity", "min_stock_level", "order_qty", "received_qty", "lead_time", "total_amount", "total_stock", "specifications", "manufacturer", "manufacturer_part_number", "material", "finish", "weight", "datasheet_url", "image_path", "cad_file_url", "pdm_file_path", "vendor_part_number", "po_number", "pdf_path", "pdf2_path", "pdf3_path", "created_date", "updated_date") VALUES ('8', 'MM-9101584', '9101584', 'BIG ROLLER FRONT -SS304', '13', '3975.00', 'INR', '0.00', 0, 0, 0, 0, NULL, '0.00', 0, NULL, 'Padmavati Engineering Solutions', NULL, 'SS304', NULL, NULL, NULL, 'https://buvzefqfoeyupxsmhgkd.supabase.co/storage/v1/object/public/bom_assets/zg7foetxlac-1775478575048.png', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-04-06T11:34:59.731Z', NULL);
INSERT INTO "mechanical_manufacture" ("id", "part_number", "beperp_part_no", "description", "supplier_id", "base_price", "currency", "discount_percent", "stock_quantity", "min_stock_level", "order_qty", "received_qty", "lead_time", "total_amount", "total_stock", "specifications", "manufacturer", "manufacturer_part_number", "material", "finish", "weight", "datasheet_url", "image_path", "cad_file_url", "pdm_file_path", "vendor_part_number", "po_number", "pdf_path", "pdf2_path", "pdf3_path", "created_date", "updated_date") VALUES ('9', 'MM-9101585', '9101585', 'SMALL ROLLER SHAFT FRONT-EN21', '13', '530.00', 'INR', '0.00', 0, 0, 0, 0, NULL, '0.00', 0, NULL, 'Padmavati Engineering Solutions', NULL, 'EN21', NULL, NULL, NULL, 'https://buvzefqfoeyupxsmhgkd.supabase.co/storage/v1/object/public/bom_assets/x1es4jday4-1775478622574.png', NULL, NULL, NULL, NULL, NULL, NULL, 'https://buvzefqfoeyupxsmhgkd.supabase.co/storage/v1/object/public/bom_assets/khd7xtb1xki-1775478638163.pdf', '2026-04-06T11:35:00.753Z', NULL);
INSERT INTO "mechanical_manufacture" ("id", "part_number", "beperp_part_no", "description", "supplier_id", "base_price", "currency", "discount_percent", "stock_quantity", "min_stock_level", "order_qty", "received_qty", "lead_time", "total_amount", "total_stock", "specifications", "manufacturer", "manufacturer_part_number", "material", "finish", "weight", "datasheet_url", "image_path", "cad_file_url", "pdm_file_path", "vendor_part_number", "po_number", "pdf_path", "pdf2_path", "pdf3_path", "created_date", "updated_date") VALUES ('10', 'MM-9101586', '9101586', 'SMALL ROLLER FRONT-SS304', '13', '1185.00', 'INR', '0.00', 0, 0, 0, 0, NULL, '0.00', 0, NULL, 'Padmavati Engineering Solutions', NULL, 'SS304', NULL, NULL, NULL, 'https://buvzefqfoeyupxsmhgkd.supabase.co/storage/v1/object/public/bom_assets/vxubida4ov8-1775478950574.png', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-04-06T11:35:01.939Z', NULL);
INSERT INTO "mechanical_manufacture" ("id", "part_number", "beperp_part_no", "description", "supplier_id", "base_price", "currency", "discount_percent", "stock_quantity", "min_stock_level", "order_qty", "received_qty", "lead_time", "total_amount", "total_stock", "specifications", "manufacturer", "manufacturer_part_number", "material", "finish", "weight", "datasheet_url", "image_path", "cad_file_url", "pdm_file_path", "vendor_part_number", "po_number", "pdf_path", "pdf2_path", "pdf3_path", "created_date", "updated_date") VALUES ('14', 'MM-9101560', '9101560', 'COLLAR-SS304', '13', '955.00', 'INR', '0.00', 1, 0, 0, 0, NULL, '0.00', 0, NULL, 'Padmavati Engineering Solutions', NULL, 'SS304', NULL, NULL, NULL, 'https://buvzefqfoeyupxsmhgkd.supabase.co/storage/v1/object/public/bom_assets/mee6bsetodf-1775478420319.png', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-04-06T11:35:08.701Z', NULL);

-- Table: mechanical_bought_out --
-- (Empty table: mechanical_bought_out)

-- Table: electrical_manufacture --
-- (Empty table: electrical_manufacture)

-- Table: electrical_bought_out --
INSERT INTO "electrical_bought_out" ("id", "part_number", "beperp_part_no", "description", "supplier_id", "base_price", "currency", "discount_percent", "stock_quantity", "min_stock_level", "order_qty", "received_qty", "lead_time", "total_amount", "total_stock", "specifications", "manufacturer", "manufacturer_part_number", "datasheet_url", "image_path", "cad_file_url", "po_number", "pdf_path", "pdf2_path", "pdf3_path", "created_date", "updated_date") VALUES ('3', '9101714', '9101714', '1734-AENTR 2-Port EtherNet I/O Adapter Module. Dual ethernet port', '9', '27517.00', 'INR', '0.00', 0, 0, 0, 0, NULL, '0.00', 0, NULL, NULL, '1734-AENTR 2-Port EtherNet I/O Adapter Module', NULL, 'https://buvzefqfoeyupxsmhgkd.supabase.co/storage/v1/object/public/bom_assets/naigzcute1h-1775456667694.jpg', NULL, NULL, NULL, NULL, NULL, '2026-04-04T11:29:47.048Z', NULL);
INSERT INTO "electrical_bought_out" ("id", "part_number", "beperp_part_no", "description", "supplier_id", "base_price", "currency", "discount_percent", "stock_quantity", "min_stock_level", "order_qty", "received_qty", "lead_time", "total_amount", "total_stock", "specifications", "manufacturer", "manufacturer_part_number", "datasheet_url", "image_path", "cad_file_url", "po_number", "pdf_path", "pdf2_path", "pdf3_path", "created_date", "updated_date") VALUES ('5', '9101661', '9101661', 'PNOZsigma Safety relay (standalone). Inputs: 1-/2-channel wiring with/ without detection of shorts across contacts. Outputs: 3 N/O, 1 N/C, 1 semiconductor, UB 24 V DC, width: 22.5 mm, Monitoring E-STOP, safety gates.', '10', '18850.00', 'INR', '0.00', 0, 0, 0, 0, NULL, '0.00', 0, NULL, NULL, '750104', NULL, 'https://buvzefqfoeyupxsmhgkd.supabase.co/storage/v1/object/public/bom_assets/y56ptwa2kb-1775458656491.png', NULL, NULL, NULL, NULL, NULL, '2026-04-06T06:57:54.309Z', NULL);
INSERT INTO "electrical_bought_out" ("id", "part_number", "beperp_part_no", "description", "supplier_id", "base_price", "currency", "discount_percent", "stock_quantity", "min_stock_level", "order_qty", "received_qty", "lead_time", "total_amount", "total_stock", "specifications", "manufacturer", "manufacturer_part_number", "datasheet_url", "image_path", "cad_file_url", "po_number", "pdf_path", "pdf2_path", "pdf3_path", "created_date", "updated_date") VALUES ('7', 'EBO-103753', NULL, 'Encoder cable with 2 connectors         ', '12', '0.00', 'INR', '0.00', 0, 0, 0, 0, NULL, '0.00', 0, 'Encoder cable with 2 connectors         ', NULL, 'MDX-B 13324535 (20m)', NULL, 'https://buvzefqfoeyupxsmhgkd.supabase.co/storage/v1/object/public/bom_assets/s34nuj9q81f-1775465563609.png', NULL, NULL, NULL, NULL, NULL, '2026-04-06T08:53:35.826Z', NULL);
INSERT INTO "electrical_bought_out" ("id", "part_number", "beperp_part_no", "description", "supplier_id", "base_price", "currency", "discount_percent", "stock_quantity", "min_stock_level", "order_qty", "received_qty", "lead_time", "total_amount", "total_stock", "specifications", "manufacturer", "manufacturer_part_number", "datasheet_url", "image_path", "cad_file_url", "po_number", "pdf_path", "pdf2_path", "pdf3_path", "created_date", "updated_date") VALUES ('9', 'EBO-766260', NULL, 'Brake motor cable with 1 connector   ', '12', '0.00', 'INR', '0.00', 0, 0, 0, 0, NULL, '0.00', 0, 'Brake motor cable with 1 connector   ', NULL, 'SB11 13354388    (20m)', NULL, 'https://buvzefqfoeyupxsmhgkd.supabase.co/storage/v1/object/public/bom_assets/1ik9ou7s5rn-1775466843860.png', NULL, NULL, NULL, NULL, NULL, '2026-04-06T09:14:17.453Z', NULL);
INSERT INTO "electrical_bought_out" ("id", "part_number", "beperp_part_no", "description", "supplier_id", "base_price", "currency", "discount_percent", "stock_quantity", "min_stock_level", "order_qty", "received_qty", "lead_time", "total_amount", "total_stock", "specifications", "manufacturer", "manufacturer_part_number", "datasheet_url", "image_path", "cad_file_url", "po_number", "pdf_path", "pdf2_path", "pdf3_path", "created_date", "updated_date") VALUES ('10', 'EBO-057240', NULL, 'Servo gearmotor                                             ', '12', '0.00', 'INR', '0.00', 0, 0, 0, 0, NULL, '0.00', 0, 'Servo gearmotor                                             ', NULL, 'KF37CMP50S/BK/PK/AK1H/SB1', NULL, 'https://buvzefqfoeyupxsmhgkd.supabase.co/storage/v1/object/public/bom_assets/f7tpjlxin0v-1775467513946.png', NULL, NULL, NULL, NULL, NULL, '2026-04-06T09:25:36.161Z', NULL);
INSERT INTO "electrical_bought_out" ("id", "part_number", "beperp_part_no", "description", "supplier_id", "base_price", "currency", "discount_percent", "stock_quantity", "min_stock_level", "order_qty", "received_qty", "lead_time", "total_amount", "total_stock", "specifications", "manufacturer", "manufacturer_part_number", "datasheet_url", "image_path", "cad_file_url", "po_number", "pdf_path", "pdf2_path", "pdf3_path", "created_date", "updated_date") VALUES ('8', 'EBO-854767', NULL, 'Frequency inverter                                        ', '12', '0.00', 'INR', '0.00', 0, 0, 0, 0, NULL, '0.00', 0, 'Frequency inverter                                        ', NULL, 'MDX61B0005-5A3-4-0T ', NULL, 'https://buvzefqfoeyupxsmhgkd.supabase.co/storage/v1/object/public/bom_assets/nrghuo09p1d-1775465849287.png', NULL, NULL, NULL, NULL, NULL, '2026-04-06T08:58:30.140Z', NULL);
INSERT INTO "electrical_bought_out" ("id", "part_number", "beperp_part_no", "description", "supplier_id", "base_price", "currency", "discount_percent", "stock_quantity", "min_stock_level", "order_qty", "received_qty", "lead_time", "total_amount", "total_stock", "specifications", "manufacturer", "manufacturer_part_number", "datasheet_url", "image_path", "cad_file_url", "po_number", "pdf_path", "pdf2_path", "pdf3_path", "created_date", "updated_date") VALUES ('11', 'EBO-641262', NULL, 'Breaking resistor', '12', '0.00', 'INR', '0.00', 0, 0, 0, 0, NULL, '0.00', 0, 'Breaking resistor', NULL, 'BW090-P52B', NULL, 'https://buvzefqfoeyupxsmhgkd.supabase.co/storage/v1/object/public/bom_assets/53lopn4iyr6-1775467689731.png', NULL, NULL, NULL, NULL, NULL, '2026-04-06T09:28:29.668Z', NULL);
INSERT INTO "electrical_bought_out" ("id", "part_number", "beperp_part_no", "description", "supplier_id", "base_price", "currency", "discount_percent", "stock_quantity", "min_stock_level", "order_qty", "received_qty", "lead_time", "total_amount", "total_stock", "specifications", "manufacturer", "manufacturer_part_number", "datasheet_url", "image_path", "cad_file_url", "po_number", "pdf_path", "pdf2_path", "pdf3_path", "created_date", "updated_date") VALUES ('12', 'EBO-624733', NULL, 'Keypad', '12', '0.00', 'INR', '0.00', 0, 0, 0, 0, NULL, '0.00', 0, 'Keypad', NULL, 'DBG60B', NULL, 'https://buvzefqfoeyupxsmhgkd.supabase.co/storage/v1/object/public/bom_assets/dag3jjsxkl-1775468688248.png', NULL, NULL, NULL, NULL, NULL, '2026-04-06T09:45:00.138Z', NULL);

-- Table: pneumatic_bought_out --
-- (Empty table: pneumatic_bought_out)

-- Table: purchase_orders --
INSERT INTO "purchase_orders" ("id", "po_number", "project_id", "supplier_id", "po_date", "status", "currency", "grand_total", "total_items", "total_quantity", "notes", "terms", "created_date", "updated_date", "bep_po_pdf_url", "expected_delivery_date") VALUES ('25', 'CPO-65506161', '9', '10', '2026-04-06T08:51:46.161Z', 'Draft', 'USD', '37700.00', 2, 0, 'Consolidated PO (Multi-Project) generated from Global Procurement Registry.', NULL, '2026-04-06T08:51:46.161Z', NULL, NULL, NULL);

-- Table: part_usage_logs --
INSERT INTO "part_usage_logs" ("id", "project_name", "site_name", "use_date_time", "part_number", "part_table_name", "quantity", "created_date") VALUES ('1', 'MG', 'Main Site', '2026-04-02T09:28:25.797Z', '3242', 'mechanical_manufacture', 0, '2026-04-02T09:28:25.797Z');

-- Table: json_excel_file_uploaded --
-- (Empty table: json_excel_file_uploaded)

-- Table: part_price_history --
INSERT INTO "part_price_history" ("id", "part_table_name", "part_id", "part_number", "old_price", "new_price", "old_currency", "new_currency", "old_discount_percent", "new_discount_percent", "change_reason", "changed_by", "changed_at") VALUES ('1', 'electrical_bought_out', '2', '1', NULL, '0.00', NULL, 'INR', NULL, '0.00', 'manual_edit', 'abey.thomas@bepindia.com', '2026-04-04T04:35:43.684Z');
INSERT INTO "part_price_history" ("id", "part_table_name", "part_id", "part_number", "old_price", "new_price", "old_currency", "new_currency", "old_discount_percent", "new_discount_percent", "change_reason", "changed_by", "changed_at") VALUES ('2', 'electrical_manufacture', '1', 'AS', NULL, '0.00', NULL, 'INR', NULL, '0.00', 'manual_edit', 'abey.thomas@bepindia.com', '2026-04-04T04:36:01.218Z');
INSERT INTO "part_price_history" ("id", "part_table_name", "part_id", "part_number", "old_price", "new_price", "old_currency", "new_currency", "old_discount_percent", "new_discount_percent", "change_reason", "changed_by", "changed_at") VALUES ('3', 'pneumatic_bought_out', '1', '655444', NULL, '0.00', NULL, 'INR', NULL, '0.00', 'manual_edit', 'abey.thomas@bepindia.com', '2026-04-04T06:53:12.319Z');
INSERT INTO "part_price_history" ("id", "part_table_name", "part_id", "part_number", "old_price", "new_price", "old_currency", "new_currency", "old_discount_percent", "new_discount_percent", "change_reason", "changed_by", "changed_at") VALUES ('5', 'electrical_bought_out', '3', '9101714', NULL, '27517.00', NULL, 'INR', NULL, NULL, 'Manual Audit', 'abey.thomas@bepindia.com', '2025-11-10T00:00:00.000Z');
INSERT INTO "part_price_history" ("id", "part_table_name", "part_id", "part_number", "old_price", "new_price", "old_currency", "new_currency", "old_discount_percent", "new_discount_percent", "change_reason", "changed_by", "changed_at") VALUES ('6', 'electrical_bought_out', '4', 'e001', NULL, '399.98', NULL, 'INR', NULL, '0.00', 'manual_edit', 'abey.thomas@bepindia.com', '2026-04-06T01:42:02.586Z');
INSERT INTO "part_price_history" ("id", "part_table_name", "part_id", "part_number", "old_price", "new_price", "old_currency", "new_currency", "old_discount_percent", "new_discount_percent", "change_reason", "changed_by", "changed_at") VALUES ('8', 'electrical_bought_out', '5', '9101661', NULL, '18850.00', 'INR', 'INR', NULL, '0.00', 'initial_entry', 'abey.thomas@bepindia.com', '2026-04-06T00:00:00.000Z');
INSERT INTO "part_price_history" ("id", "part_table_name", "part_id", "part_number", "old_price", "new_price", "old_currency", "new_currency", "old_discount_percent", "new_discount_percent", "change_reason", "changed_by", "changed_at") VALUES ('9', 'electrical_bought_out', '5', '9101661', NULL, '24000.00', NULL, 'INR', NULL, NULL, 'Manual Audit', 'abey.thomas@bepindia.com', '2024-08-24T00:00:00.000Z');
INSERT INTO "part_price_history" ("id", "part_table_name", "part_id", "part_number", "old_price", "new_price", "old_currency", "new_currency", "old_discount_percent", "new_discount_percent", "change_reason", "changed_by", "changed_at") VALUES ('10', 'electrical_bought_out', '6', '12333', NULL, '0.00', 'INR', 'INR', NULL, '0.00', 'initial_entry', 'abey.thomas@bepindia.com', '2026-04-06T00:00:00.000Z');
INSERT INTO "part_price_history" ("id", "part_table_name", "part_id", "part_number", "old_price", "new_price", "old_currency", "new_currency", "old_discount_percent", "new_discount_percent", "change_reason", "changed_by", "changed_at") VALUES ('11', 'mechanical_manufacture', '3', 'BW090-P52B', NULL, '0.00', 'INR', 'INR', NULL, '0.00', 'initial_entry', 'sachin.chaudhary@bepindia.com', '2026-04-06T08:08:52.174Z');
INSERT INTO "part_price_history" ("id", "part_table_name", "part_id", "part_number", "old_price", "new_price", "old_currency", "new_currency", "old_discount_percent", "new_discount_percent", "change_reason", "changed_by", "changed_at") VALUES ('12', 'mechanical_manufacture', '4', 'MDX-B 13324535 (20m)', NULL, '0.00', 'INR', 'INR', NULL, '0.00', 'initial_entry', 'sachin.chaudhary@bepindia.com', '2026-04-06T08:49:53.757Z');
INSERT INTO "part_price_history" ("id", "part_table_name", "part_id", "part_number", "old_price", "new_price", "old_currency", "new_currency", "old_discount_percent", "new_discount_percent", "change_reason", "changed_by", "changed_at") VALUES ('13', 'electrical_bought_out', '7', 'MDX-B 13324535 (20m)', NULL, '0.00', 'INR', 'INR', NULL, '0.00', 'initial_entry', 'sachin.chaudhary@bepindia.com', '2026-04-06T08:53:26.934Z');
INSERT INTO "part_price_history" ("id", "part_table_name", "part_id", "part_number", "old_price", "new_price", "old_currency", "new_currency", "old_discount_percent", "new_discount_percent", "change_reason", "changed_by", "changed_at") VALUES ('14', 'electrical_bought_out', '8', 'MDX61B0005-5A3-4-0T    ', NULL, '0.00', 'INR', 'INR', NULL, '0.00', 'initial_entry', 'sachin.chaudhary@bepindia.com', '2026-04-06T08:58:21.265Z');
INSERT INTO "part_price_history" ("id", "part_table_name", "part_id", "part_number", "old_price", "new_price", "old_currency", "new_currency", "old_discount_percent", "new_discount_percent", "change_reason", "changed_by", "changed_at") VALUES ('15', 'electrical_bought_out', '9', 'EBO-766260', NULL, '0.00', 'INR', 'INR', NULL, '0.00', 'initial_entry', 'sachin.chaudhary@bepindia.com', '2026-04-06T09:14:08.581Z');
INSERT INTO "part_price_history" ("id", "part_table_name", "part_id", "part_number", "old_price", "new_price", "old_currency", "new_currency", "old_discount_percent", "new_discount_percent", "change_reason", "changed_by", "changed_at") VALUES ('16', 'electrical_bought_out', '10', 'EBO-057240', NULL, '0.00', 'INR', 'INR', NULL, '0.00', 'initial_entry', 'sachin.chaudhary@bepindia.com', '2026-04-06T09:25:27.302Z');
INSERT INTO "part_price_history" ("id", "part_table_name", "part_id", "part_number", "old_price", "new_price", "old_currency", "new_currency", "old_discount_percent", "new_discount_percent", "change_reason", "changed_by", "changed_at") VALUES ('17', 'electrical_bought_out', '11', 'EBO-641262', NULL, '0.00', 'INR', 'INR', NULL, '0.00', 'initial_entry', 'sachin.chaudhary@bepindia.com', '2026-04-06T09:28:20.822Z');
INSERT INTO "part_price_history" ("id", "part_table_name", "part_id", "part_number", "old_price", "new_price", "old_currency", "new_currency", "old_discount_percent", "new_discount_percent", "change_reason", "changed_by", "changed_at") VALUES ('18', 'electrical_bought_out', '12', 'EBO-624733', NULL, '0.00', 'INR', 'INR', NULL, '0.00', 'initial_entry', 'sachin.chaudhary@bepindia.com', '2026-04-06T09:44:51.303Z');
INSERT INTO "part_price_history" ("id", "part_table_name", "part_id", "part_number", "old_price", "new_price", "old_currency", "new_currency", "old_discount_percent", "new_discount_percent", "change_reason", "changed_by", "changed_at") VALUES ('19', 'mechanical_bought_out', '1', 'MBO-9101581', NULL, '965.00', 'INR', 'INR', NULL, '0.00', 'json_import', 'abey.thomas@bepindia.com', '2026-04-06T11:29:08.299Z');
INSERT INTO "part_price_history" ("id", "part_table_name", "part_id", "part_number", "old_price", "new_price", "old_currency", "new_currency", "old_discount_percent", "new_discount_percent", "change_reason", "changed_by", "changed_at") VALUES ('20', 'mechanical_bought_out', '2', 'MBO-9101582', NULL, '3925.00', 'INR', 'INR', NULL, '0.00', 'json_import', 'abey.thomas@bepindia.com', '2026-04-06T11:29:10.994Z');
INSERT INTO "part_price_history" ("id", "part_table_name", "part_id", "part_number", "old_price", "new_price", "old_currency", "new_currency", "old_discount_percent", "new_discount_percent", "change_reason", "changed_by", "changed_at") VALUES ('21', 'mechanical_bought_out', '3', 'MBO-9101583', NULL, '1015.00', 'INR', 'INR', NULL, '0.00', 'json_import', 'abey.thomas@bepindia.com', '2026-04-06T11:29:12.820Z');
INSERT INTO "part_price_history" ("id", "part_table_name", "part_id", "part_number", "old_price", "new_price", "old_currency", "new_currency", "old_discount_percent", "new_discount_percent", "change_reason", "changed_by", "changed_at") VALUES ('22', 'mechanical_bought_out', '4', 'MBO-9101584', NULL, '3975.00', 'INR', 'INR', NULL, '0.00', 'json_import', 'abey.thomas@bepindia.com', '2026-04-06T11:29:13.917Z');
INSERT INTO "part_price_history" ("id", "part_table_name", "part_id", "part_number", "old_price", "new_price", "old_currency", "new_currency", "old_discount_percent", "new_discount_percent", "change_reason", "changed_by", "changed_at") VALUES ('23', 'mechanical_bought_out', '5', 'MBO-9101585', NULL, '530.00', 'INR', 'INR', NULL, '0.00', 'json_import', 'abey.thomas@bepindia.com', '2026-04-06T11:29:15.116Z');
INSERT INTO "part_price_history" ("id", "part_table_name", "part_id", "part_number", "old_price", "new_price", "old_currency", "new_currency", "old_discount_percent", "new_discount_percent", "change_reason", "changed_by", "changed_at") VALUES ('24', 'mechanical_bought_out', '6', 'MBO-9101586', NULL, '1185.00', 'INR', 'INR', NULL, '0.00', 'json_import', 'abey.thomas@bepindia.com', '2026-04-06T11:29:16.272Z');
INSERT INTO "part_price_history" ("id", "part_table_name", "part_id", "part_number", "old_price", "new_price", "old_currency", "new_currency", "old_discount_percent", "new_discount_percent", "change_reason", "changed_by", "changed_at") VALUES ('25', 'mechanical_bought_out', '7', 'MBO-9101587', NULL, '170.00', 'INR', 'INR', NULL, '0.00', 'json_import', 'abey.thomas@bepindia.com', '2026-04-06T11:29:17.542Z');
INSERT INTO "part_price_history" ("id", "part_table_name", "part_id", "part_number", "old_price", "new_price", "old_currency", "new_currency", "old_discount_percent", "new_discount_percent", "change_reason", "changed_by", "changed_at") VALUES ('26', 'mechanical_bought_out', '8', 'MBO-9101588', NULL, '295.00', 'INR', 'INR', NULL, '0.00', 'json_import', 'abey.thomas@bepindia.com', '2026-04-06T11:29:20.930Z');
INSERT INTO "part_price_history" ("id", "part_table_name", "part_id", "part_number", "old_price", "new_price", "old_currency", "new_currency", "old_discount_percent", "new_discount_percent", "change_reason", "changed_by", "changed_at") VALUES ('27', 'mechanical_bought_out', '9', 'MBO-9101589', NULL, '1100.00', 'INR', 'INR', NULL, '0.00', 'json_import', 'abey.thomas@bepindia.com', '2026-04-06T11:29:23.444Z');
INSERT INTO "part_price_history" ("id", "part_table_name", "part_id", "part_number", "old_price", "new_price", "old_currency", "new_currency", "old_discount_percent", "new_discount_percent", "change_reason", "changed_by", "changed_at") VALUES ('28', 'mechanical_bought_out', '10', 'MBO-9101560', NULL, '955.00', 'INR', 'INR', NULL, '0.00', 'json_import', 'abey.thomas@bepindia.com', '2026-04-06T11:29:25.569Z');
INSERT INTO "part_price_history" ("id", "part_table_name", "part_id", "part_number", "old_price", "new_price", "old_currency", "new_currency", "old_discount_percent", "new_discount_percent", "change_reason", "changed_by", "changed_at") VALUES ('29', 'mechanical_manufacture', '5', 'MM-9101581', NULL, '965.00', 'INR', 'INR', NULL, '0.00', 'json_import', 'abey.thomas@bepindia.com', '2026-04-06T11:34:55.565Z');
INSERT INTO "part_price_history" ("id", "part_table_name", "part_id", "part_number", "old_price", "new_price", "old_currency", "new_currency", "old_discount_percent", "new_discount_percent", "change_reason", "changed_by", "changed_at") VALUES ('30', 'mechanical_manufacture', '6', 'MM-9101582', NULL, '3925.00', 'INR', 'INR', NULL, '0.00', 'json_import', 'abey.thomas@bepindia.com', '2026-04-06T11:34:56.689Z');
INSERT INTO "part_price_history" ("id", "part_table_name", "part_id", "part_number", "old_price", "new_price", "old_currency", "new_currency", "old_discount_percent", "new_discount_percent", "change_reason", "changed_by", "changed_at") VALUES ('31', 'mechanical_manufacture', '7', 'MM-9101583', NULL, '1015.00', 'INR', 'INR', NULL, '0.00', 'json_import', 'abey.thomas@bepindia.com', '2026-04-06T11:34:59.033Z');
INSERT INTO "part_price_history" ("id", "part_table_name", "part_id", "part_number", "old_price", "new_price", "old_currency", "new_currency", "old_discount_percent", "new_discount_percent", "change_reason", "changed_by", "changed_at") VALUES ('32', 'mechanical_manufacture', '8', 'MM-9101584', NULL, '3975.00', 'INR', 'INR', NULL, '0.00', 'json_import', 'abey.thomas@bepindia.com', '2026-04-06T11:35:00.117Z');
INSERT INTO "part_price_history" ("id", "part_table_name", "part_id", "part_number", "old_price", "new_price", "old_currency", "new_currency", "old_discount_percent", "new_discount_percent", "change_reason", "changed_by", "changed_at") VALUES ('33', 'mechanical_manufacture', '9', 'MM-9101585', NULL, '530.00', 'INR', 'INR', NULL, '0.00', 'json_import', 'abey.thomas@bepindia.com', '2026-04-06T11:35:01.256Z');
INSERT INTO "part_price_history" ("id", "part_table_name", "part_id", "part_number", "old_price", "new_price", "old_currency", "new_currency", "old_discount_percent", "new_discount_percent", "change_reason", "changed_by", "changed_at") VALUES ('34', 'mechanical_manufacture', '10', 'MM-9101586', NULL, '1185.00', 'INR', 'INR', NULL, '0.00', 'json_import', 'abey.thomas@bepindia.com', '2026-04-06T11:35:02.398Z');
INSERT INTO "part_price_history" ("id", "part_table_name", "part_id", "part_number", "old_price", "new_price", "old_currency", "new_currency", "old_discount_percent", "new_discount_percent", "change_reason", "changed_by", "changed_at") VALUES ('35', 'mechanical_manufacture', '11', 'MM-9101587', NULL, '170.00', 'INR', 'INR', NULL, '0.00', 'json_import', 'abey.thomas@bepindia.com', '2026-04-06T11:35:03.482Z');
INSERT INTO "part_price_history" ("id", "part_table_name", "part_id", "part_number", "old_price", "new_price", "old_currency", "new_currency", "old_discount_percent", "new_discount_percent", "change_reason", "changed_by", "changed_at") VALUES ('36', 'mechanical_manufacture', '12', 'MM-9101588', NULL, '295.00', 'INR', 'INR', NULL, '0.00', 'json_import', 'abey.thomas@bepindia.com', '2026-04-06T11:35:04.629Z');
INSERT INTO "part_price_history" ("id", "part_table_name", "part_id", "part_number", "old_price", "new_price", "old_currency", "new_currency", "old_discount_percent", "new_discount_percent", "change_reason", "changed_by", "changed_at") VALUES ('37', 'mechanical_manufacture', '13', 'MM-9101589', NULL, '1100.00', 'INR', 'INR', NULL, '0.00', 'json_import', 'abey.thomas@bepindia.com', '2026-04-06T11:35:05.871Z');
INSERT INTO "part_price_history" ("id", "part_table_name", "part_id", "part_number", "old_price", "new_price", "old_currency", "new_currency", "old_discount_percent", "new_discount_percent", "change_reason", "changed_by", "changed_at") VALUES ('38', 'mechanical_manufacture', '14', 'MM-9101560', NULL, '955.00', 'INR', 'INR', NULL, '0.00', 'json_import', 'abey.thomas@bepindia.com', '2026-04-06T11:35:09.159Z');

-- Table: purchase_order_items --
INSERT INTO "purchase_order_items" ("id", "purchase_order_id", "part_type", "part_number", "description", "quantity", "unit_price", "discount_percent", "total_amount", "project_part_id") VALUES ('12', '25', 'electrical_bought_out', '9101661', 'PNOZsigma Safety relay (standalone). Inputs: 1-/2-channel wiring with/ without detection of shorts across contacts. Outputs: 3 N/O, 1 N/C, 1 semiconductor, UB 24 V DC, width: 22.5 mm, Monitoring E-STOP, safety gates.', 1, '18850.00', '0.00', '18850.00', '6');
INSERT INTO "purchase_order_items" ("id", "purchase_order_id", "part_type", "part_number", "description", "quantity", "unit_price", "discount_percent", "total_amount", "project_part_id") VALUES ('13', '25', 'electrical_bought_out', '9101661', 'PNOZsigma Safety relay (standalone). Inputs: 1-/2-channel wiring with/ without detection of shorts across contacts. Outputs: 3 N/O, 1 N/C, 1 semiconductor, UB 24 V DC, width: 22.5 mm, Monitoring E-STOP, safety gates.', 1, '18850.00', '0.00', '18850.00', '7');

-- Table: stock_movements --
INSERT INTO "stock_movements" ("id", "movement_type", "part_table_name", "part_id", "part_number", "quantity", "stock_before", "stock_after", "supplier_id", "supplier_name", "po_number", "project_name", "project_id", "project_section_name", "site_name", "reference_notes", "unit_price_at_movement", "currency", "moved_by", "moved_at", "created_date") VALUES ('9', 'OUT', 'electrical_bought_out', '3', '9101714', -1, 0, -1, NULL, NULL, NULL, 'MG LM6- REAR GANTRY', '9', 'pNEUMATIC', NULL, NULL, NULL, 'INR', 'abey.thomas@bepindia.com', '2026-04-06T03:21:52.383Z', '2026-04-06T03:21:52.383Z');
INSERT INTO "stock_movements" ("id", "movement_type", "part_table_name", "part_id", "part_number", "quantity", "stock_before", "stock_after", "supplier_id", "supplier_name", "po_number", "project_name", "project_id", "project_section_name", "site_name", "reference_notes", "unit_price_at_movement", "currency", "moved_by", "moved_at", "created_date") VALUES ('10', 'OUT', 'electrical_bought_out', '5', '9101661', -1, 0, -1, NULL, NULL, NULL, 'MG LM6- REAR GANTRY', '9', 'Safety', NULL, NULL, NULL, 'INR', 'abey.thomas@bepindia.com', '2026-04-06T07:04:02.554Z', '2026-04-06T07:04:02.554Z');
INSERT INTO "stock_movements" ("id", "movement_type", "part_table_name", "part_id", "part_number", "quantity", "stock_before", "stock_after", "supplier_id", "supplier_name", "po_number", "project_name", "project_id", "project_section_name", "site_name", "reference_notes", "unit_price_at_movement", "currency", "moved_by", "moved_at", "created_date") VALUES ('11', 'OUT', 'electrical_bought_out', '6', '12333', -1, 0, -1, NULL, NULL, NULL, 'MG LM6- REAR GANTRY', '9', 'Servo Motor ', NULL, NULL, NULL, 'INR', 'sachin.chaudhary@bepindia.com', '2026-04-06T07:36:11.279Z', '2026-04-06T07:36:11.279Z');
INSERT INTO "stock_movements" ("id", "movement_type", "part_table_name", "part_id", "part_number", "quantity", "stock_before", "stock_after", "supplier_id", "supplier_name", "po_number", "project_name", "project_id", "project_section_name", "site_name", "reference_notes", "unit_price_at_movement", "currency", "moved_by", "moved_at", "created_date") VALUES ('12', 'OUT', 'electrical_bought_out', '8', 'MDX61B0005-5A3-4-0T    ', -1, 0, -1, NULL, NULL, NULL, 'MG LM6- REAR GANTRY', '9', 'Servo Motor ', NULL, NULL, NULL, 'INR', 'sachin.chaudhary@bepindia.com', '2026-04-06T09:00:11.511Z', '2026-04-06T09:00:11.511Z');
INSERT INTO "stock_movements" ("id", "movement_type", "part_table_name", "part_id", "part_number", "quantity", "stock_before", "stock_after", "supplier_id", "supplier_name", "po_number", "project_name", "project_id", "project_section_name", "site_name", "reference_notes", "unit_price_at_movement", "currency", "moved_by", "moved_at", "created_date") VALUES ('13', 'OUT', 'electrical_bought_out', '7', 'MDX-B 13324535 (20m)', -1, 0, -1, NULL, NULL, NULL, 'MG LM6- REAR GANTRY', '9', 'Servo Motor ', NULL, NULL, NULL, 'INR', 'sachin.chaudhary@bepindia.com', '2026-04-06T09:00:27.561Z', '2026-04-06T09:00:27.561Z');
INSERT INTO "stock_movements" ("id", "movement_type", "part_table_name", "part_id", "part_number", "quantity", "stock_before", "stock_after", "supplier_id", "supplier_name", "po_number", "project_name", "project_id", "project_section_name", "site_name", "reference_notes", "unit_price_at_movement", "currency", "moved_by", "moved_at", "created_date") VALUES ('14', 'RESTORE', 'electrical_bought_out', '6', '12333', 1, 0, 1, NULL, NULL, NULL, 'MG LM6- REAR GANTRY', '9', NULL, NULL, NULL, NULL, 'INR', 'sachin.chaudhary@bepindia.com', '2026-04-06T09:00:48.364Z', '2026-04-06T09:00:48.364Z');
INSERT INTO "stock_movements" ("id", "movement_type", "part_table_name", "part_id", "part_number", "quantity", "stock_before", "stock_after", "supplier_id", "supplier_name", "po_number", "project_name", "project_id", "project_section_name", "site_name", "reference_notes", "unit_price_at_movement", "currency", "moved_by", "moved_at", "created_date") VALUES ('15', 'OUT', 'electrical_bought_out', '9', 'EBO-766260', -1, 0, -1, NULL, NULL, NULL, 'MG LM6- REAR GANTRY', '9', 'Servo Motor ', NULL, NULL, NULL, 'INR', 'sachin.chaudhary@bepindia.com', '2026-04-06T09:14:49.908Z', '2026-04-06T09:14:49.908Z');
INSERT INTO "stock_movements" ("id", "movement_type", "part_table_name", "part_id", "part_number", "quantity", "stock_before", "stock_after", "supplier_id", "supplier_name", "po_number", "project_name", "project_id", "project_section_name", "site_name", "reference_notes", "unit_price_at_movement", "currency", "moved_by", "moved_at", "created_date") VALUES ('16', 'OUT', 'electrical_bought_out', '10', 'EBO-057240', -1, 0, -1, NULL, NULL, NULL, 'MG LM6- REAR GANTRY', '9', 'Servo Motor ', NULL, NULL, NULL, 'INR', 'sachin.chaudhary@bepindia.com', '2026-04-06T09:32:08.738Z', '2026-04-06T09:32:08.738Z');
INSERT INTO "stock_movements" ("id", "movement_type", "part_table_name", "part_id", "part_number", "quantity", "stock_before", "stock_after", "supplier_id", "supplier_name", "po_number", "project_name", "project_id", "project_section_name", "site_name", "reference_notes", "unit_price_at_movement", "currency", "moved_by", "moved_at", "created_date") VALUES ('17', 'OUT', 'electrical_bought_out', '10', 'EBO-057240', -1, 0, -1, NULL, NULL, NULL, 'MG LM6- REAR GANTRY', '9', 'Servo Motor ', NULL, NULL, NULL, 'INR', 'sachin.chaudhary@bepindia.com', '2026-04-06T09:33:35.571Z', '2026-04-06T09:33:35.571Z');
INSERT INTO "stock_movements" ("id", "movement_type", "part_table_name", "part_id", "part_number", "quantity", "stock_before", "stock_after", "supplier_id", "supplier_name", "po_number", "project_name", "project_id", "project_section_name", "site_name", "reference_notes", "unit_price_at_movement", "currency", "moved_by", "moved_at", "created_date") VALUES ('18', 'OUT', 'electrical_bought_out', '11', 'EBO-641262', -1, 0, -1, NULL, NULL, NULL, 'MG LM6- REAR GANTRY', '9', 'Servo Motor ', NULL, NULL, NULL, 'INR', 'sachin.chaudhary@bepindia.com', '2026-04-06T09:34:00.674Z', '2026-04-06T09:34:00.674Z');
INSERT INTO "stock_movements" ("id", "movement_type", "part_table_name", "part_id", "part_number", "quantity", "stock_before", "stock_after", "supplier_id", "supplier_name", "po_number", "project_name", "project_id", "project_section_name", "site_name", "reference_notes", "unit_price_at_movement", "currency", "moved_by", "moved_at", "created_date") VALUES ('19', 'OUT', 'electrical_bought_out', '12', 'EBO-624733', -1, 0, -1, NULL, NULL, NULL, 'MG LM6- REAR GANTRY', '9', 'Servo Motor ', NULL, NULL, NULL, 'INR', 'sachin.chaudhary@bepindia.com', '2026-04-06T09:47:04.913Z', '2026-04-06T09:47:04.913Z');
INSERT INTO "stock_movements" ("id", "movement_type", "part_table_name", "part_id", "part_number", "quantity", "stock_before", "stock_after", "supplier_id", "supplier_name", "po_number", "project_name", "project_id", "project_section_name", "site_name", "reference_notes", "unit_price_at_movement", "currency", "moved_by", "moved_at", "created_date") VALUES ('20', 'OUT', 'mechanical_manufacture', '14', 'MM-9101560', -1, 0, -1, NULL, NULL, NULL, 'MG LM6 CAMERA CALIBRATION', '7', 'Roller', NULL, NULL, NULL, 'INR', 'abey.thomas@bepindia.com', '2026-04-06T12:45:14.099Z', '2026-04-06T12:45:14.099Z');
INSERT INTO "stock_movements" ("id", "movement_type", "part_table_name", "part_id", "part_number", "quantity", "stock_before", "stock_after", "supplier_id", "supplier_name", "po_number", "project_name", "project_id", "project_section_name", "site_name", "reference_notes", "unit_price_at_movement", "currency", "moved_by", "moved_at", "created_date") VALUES ('21', 'RESTORE', 'mechanical_manufacture', '14', 'MM-9101560', 1, 0, 1, NULL, NULL, NULL, 'MG LM6 CAMERA CALIBRATION', '7', NULL, NULL, NULL, NULL, 'INR', 'abey.thomas@bepindia.com', '2026-04-06T12:46:04.867Z', '2026-04-06T12:46:04.867Z');

-- Table: project_parts --
-- (Empty table: project_parts)

-- Table: profiles --
INSERT INTO "profiles" ("id", "role", "full_name", "created_date", "updated_date", "email") VALUES ('aafa2b25-e7d7-4a19-a462-b2e3511920af', 'user', NULL, '2026-04-04T11:00:51.964Z', '2026-04-04T11:00:51.964Z', 'rishikesh.mahale@bepindia.com');
INSERT INTO "profiles" ("id", "role", "full_name", "created_date", "updated_date", "email") VALUES ('5f8e3b0f-886f-4082-8ac3-75c7df4cd766', 'admin', 'Abey Thomas', '2026-04-04T11:06:09.874Z', '2026-04-04T11:06:09.874Z', 'abey.thomas@bepindia.com');
INSERT INTO "profiles" ("id", "role", "full_name", "created_date", "updated_date", "email") VALUES ('d4da5f2f-9f82-4f88-85a5-518c3ce709a4', 'user', NULL, '2026-04-04T11:16:23.374Z', '2026-04-04T11:16:23.374Z', NULL);
INSERT INTO "profiles" ("id", "role", "full_name", "created_date", "updated_date", "email") VALUES ('9d364cfe-1454-4a9a-a700-0be57996721b', 'user', NULL, '2026-04-06T06:44:49.241Z', '2026-04-06T06:44:49.241Z', NULL);

-- Table: project_sections --
-- (Empty table: project_sections)

