-- ================================================================
-- BOM MANAGER / ENGINEFLOW-PM — SUPABASE SCHEMA
-- ================================================================
-- Run this ENTIRE file in the Supabase SQL Editor.
-- Go to: Dashboard → SQL Editor → New Query → Paste → Run
-- ================================================================

-- ================================================================
-- PART 1: TABLES
-- ================================================================

-- --------------------------------------------------------
-- suppliers
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS suppliers (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name            TEXT NOT NULL,
  contact_person  TEXT,
  email           TEXT,
  phone           TEXT,
  address         TEXT,
  payment_terms   TEXT,
  notes           TEXT,
  created_date    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_date    TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_suppliers_name ON suppliers(name);

-- --------------------------------------------------------
-- projects
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS projects (
  id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_name                TEXT NOT NULL,
  project_number              TEXT NOT NULL UNIQUE,
  customer                    TEXT,
  description                 TEXT,
  status                      TEXT NOT NULL DEFAULT 'planning'
                                CHECK (status IN ('planning','design','build','testing','completed','on_hold','cancelled')),
  start_date                  DATE,
  target_completion_date      DATE,
  actual_completion_date      DATE,
  mechanical_design_status    TEXT DEFAULT 'not_started',
  ee_design_status            TEXT DEFAULT 'not_started',
  pneumatic_design_status     TEXT DEFAULT 'not_started',
  po_release_status           TEXT DEFAULT 'not_started',
  part_arrival_status         TEXT DEFAULT 'not_started',
  machine_build_status        TEXT DEFAULT 'not_started',
  created_date                TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_date                TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_projects_status ON projects(status);
CREATE INDEX IF NOT EXISTS idx_projects_number ON projects(project_number);

-- --------------------------------------------------------
-- project_sections
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS project_sections (
  id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id              BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  section_name            TEXT NOT NULL,
  description             TEXT,
  status                  TEXT NOT NULL DEFAULT 'planning',
  estimated_cost          NUMERIC(18, 2),
  actual_cost             NUMERIC(18, 2),
  start_date              DATE,
  target_completion_date  DATE,
  sort_order              INT DEFAULT 0,
  created_date            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_date            TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_sections_project ON project_sections(project_id);

-- --------------------------------------------------------
-- mechanical_manufacture
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS mechanical_manufacture (
  id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  part_number             TEXT NOT NULL UNIQUE,
  beperp_part_no          TEXT,
  description             TEXT,
  supplier_id             BIGINT REFERENCES suppliers(id) ON DELETE SET NULL,
  base_price              NUMERIC(18, 2) NOT NULL DEFAULT 0,
  currency                TEXT NOT NULL DEFAULT 'INR',
  discount_percent        NUMERIC(5, 2) NOT NULL DEFAULT 0,
  stock_quantity          INT NOT NULL DEFAULT 0,
  min_stock_level         INT NOT NULL DEFAULT 0,
  order_qty               INT NOT NULL DEFAULT 0,
  received_qty            INT NOT NULL DEFAULT 0,
  lead_time               TEXT,
  total_amount            NUMERIC(18, 2) NOT NULL DEFAULT 0,
  total_stock             INT NOT NULL DEFAULT 0,
  specifications          TEXT,
  manufacturer            TEXT,
  manufacturer_part_number TEXT,
  material                TEXT,
  finish                  TEXT,
  weight                  NUMERIC(10, 4),
  datasheet_url           TEXT,
  image_path              TEXT,   -- Supabase Storage path (drawings bucket)
  cad_file_url            TEXT,
  pdm_file_path           TEXT,
  vendor_part_number      TEXT,
  po_number               TEXT,
  pdf_path                TEXT,   -- Supabase Storage path
  pdf2_path               TEXT,
  pdf3_path               TEXT,
  created_date            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_date            TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_mm_part_number ON mechanical_manufacture(part_number);
CREATE INDEX IF NOT EXISTS idx_mm_supplier ON mechanical_manufacture(supplier_id);

-- --------------------------------------------------------
-- mechanical_bought_out
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS mechanical_bought_out (
  id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  part_number             TEXT NOT NULL UNIQUE,
  beperp_part_no          TEXT,
  description             TEXT,
  supplier_id             BIGINT REFERENCES suppliers(id) ON DELETE SET NULL,
  base_price              NUMERIC(18, 2) NOT NULL DEFAULT 0,
  currency                TEXT NOT NULL DEFAULT 'INR',
  discount_percent        NUMERIC(5, 2) NOT NULL DEFAULT 0,
  stock_quantity          INT NOT NULL DEFAULT 0,
  min_stock_level         INT NOT NULL DEFAULT 0,
  order_qty               INT NOT NULL DEFAULT 0,
  received_qty            INT NOT NULL DEFAULT 0,
  lead_time               TEXT,
  total_amount            NUMERIC(18, 2) NOT NULL DEFAULT 0,
  total_stock             INT NOT NULL DEFAULT 0,
  specifications          TEXT,
  manufacturer            TEXT,
  manufacturer_part_number TEXT,
  material                TEXT,
  finish                  TEXT,
  weight                  NUMERIC(10, 4),
  datasheet_url           TEXT,
  image_path              TEXT,
  cad_file_url            TEXT,
  pdm_file_path           TEXT,
  vendor_part_number      TEXT,
  po_number               TEXT,
  pdf_path                TEXT,
  pdf2_path               TEXT,
  pdf3_path               TEXT,
  created_date            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_date            TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_mbo_part_number ON mechanical_bought_out(part_number);
CREATE INDEX IF NOT EXISTS idx_mbo_supplier ON mechanical_bought_out(supplier_id);

-- --------------------------------------------------------
-- electrical_manufacture
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS electrical_manufacture (
  id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  part_number             TEXT NOT NULL UNIQUE,
  beperp_part_no          TEXT,
  description             TEXT,
  supplier_id             BIGINT REFERENCES suppliers(id) ON DELETE SET NULL,
  base_price              NUMERIC(18, 2) NOT NULL DEFAULT 0,
  currency                TEXT NOT NULL DEFAULT 'INR',
  discount_percent        NUMERIC(5, 2) NOT NULL DEFAULT 0,
  stock_quantity          INT NOT NULL DEFAULT 0,
  min_stock_level         INT NOT NULL DEFAULT 0,
  order_qty               INT NOT NULL DEFAULT 0,
  received_qty            INT NOT NULL DEFAULT 0,
  lead_time               TEXT,
  total_amount            NUMERIC(18, 2) NOT NULL DEFAULT 0,
  total_stock             INT NOT NULL DEFAULT 0,
  specifications          TEXT,
  manufacturer            TEXT,
  manufacturer_part_number TEXT,
  datasheet_url           TEXT,
  image_path              TEXT,
  cad_file_url            TEXT,
  po_number               TEXT,
  pdf_path                TEXT,
  pdf2_path               TEXT,
  pdf3_path               TEXT,
  created_date            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_date            TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_em_part_number ON electrical_manufacture(part_number);
CREATE INDEX IF NOT EXISTS idx_em_supplier ON electrical_manufacture(supplier_id);

-- --------------------------------------------------------
-- electrical_bought_out
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS electrical_bought_out (
  id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  part_number             TEXT NOT NULL UNIQUE,
  beperp_part_no          TEXT,
  description             TEXT,
  supplier_id             BIGINT REFERENCES suppliers(id) ON DELETE SET NULL,
  base_price              NUMERIC(18, 2) NOT NULL DEFAULT 0,
  currency                TEXT NOT NULL DEFAULT 'INR',
  discount_percent        NUMERIC(5, 2) NOT NULL DEFAULT 0,
  stock_quantity          INT NOT NULL DEFAULT 0,
  min_stock_level         INT NOT NULL DEFAULT 0,
  order_qty               INT NOT NULL DEFAULT 0,
  received_qty            INT NOT NULL DEFAULT 0,
  lead_time               TEXT,
  total_amount            NUMERIC(18, 2) NOT NULL DEFAULT 0,
  total_stock             INT NOT NULL DEFAULT 0,
  specifications          TEXT,
  manufacturer            TEXT,
  manufacturer_part_number TEXT,
  datasheet_url           TEXT,
  image_path              TEXT,
  cad_file_url            TEXT,
  po_number               TEXT,
  pdf_path                TEXT,
  pdf2_path               TEXT,
  pdf3_path               TEXT,
  created_date            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_date            TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_ebo_part_number ON electrical_bought_out(part_number);
CREATE INDEX IF NOT EXISTS idx_ebo_supplier ON electrical_bought_out(supplier_id);

-- --------------------------------------------------------
-- pneumatic_bought_out
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS pneumatic_bought_out (
  id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  part_number              TEXT NOT NULL UNIQUE,
  beperp_part_no           TEXT,
  description              TEXT,
  supplier_id              BIGINT REFERENCES suppliers(id) ON DELETE SET NULL,
  base_price               NUMERIC(18, 2) NOT NULL DEFAULT 0,
  currency                 TEXT NOT NULL DEFAULT 'INR',
  discount_percent         NUMERIC(5, 2) NOT NULL DEFAULT 0,
  stock_quantity           INT NOT NULL DEFAULT 0,
  min_stock_level          INT NOT NULL DEFAULT 0,
  order_qty                INT NOT NULL DEFAULT 0,
  received_qty             INT NOT NULL DEFAULT 0,
  lead_time                TEXT,
  total_amount             NUMERIC(18, 2) NOT NULL DEFAULT 0,
  total_stock              INT NOT NULL DEFAULT 0,
  specifications           TEXT,
  manufacturer             TEXT,
  manufacturer_part_number TEXT,
  port_size                TEXT,
  operating_pressure       TEXT,
  datasheet_url            TEXT,
  image_path               TEXT,
  cad_file_url             TEXT,
  po_number                TEXT,
  pdf_path                 TEXT,
  pdf2_path                TEXT,
  pdf3_path                TEXT,
  created_date             TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_date             TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_pbo_part_number ON pneumatic_bought_out(part_number);
CREATE INDEX IF NOT EXISTS idx_pbo_supplier ON pneumatic_bought_out(supplier_id);

-- --------------------------------------------------------
-- project_parts  (junction: project_sections <-> any part)
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS project_parts (
  id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_section_id          BIGINT NOT NULL REFERENCES project_sections(id) ON DELETE CASCADE,
  
  -- Explicit foreign keys for each part type (Legacy Compatibility)
  mechanical_manufacture_id   BIGINT REFERENCES mechanical_manufacture(id) ON DELETE SET NULL,
  mechanical_bought_out_part_id BIGINT REFERENCES mechanical_bought_out(id) ON DELETE SET NULL,
  electrical_manufacture_id   BIGINT REFERENCES electrical_manufacture(id) ON DELETE SET NULL,
  electrical_bought_out_part_id BIGINT REFERENCES electrical_bought_out(id) ON DELETE SET NULL,
  pneumatic_bought_out_part_id BIGINT REFERENCES pneumatic_bought_out(id) ON DELETE SET NULL,

  quantity                    INT NOT NULL DEFAULT 0,
  unit_price                  NUMERIC(18, 2) NOT NULL DEFAULT 0,
  currency                    TEXT DEFAULT 'INR',
  reference_designator        TEXT,
  notes                       TEXT,
  
  -- Denormalized for consolidated usage tracking & audit
  project_name                TEXT,
  use_date_time               TIMESTAMPTZ DEFAULT NOW(),
  part_number                 TEXT,
  part_table_name             TEXT,

  created_date                TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_date                TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_project_parts_section ON project_parts(project_section_id);
CREATE INDEX IF NOT EXISTS idx_project_parts_mech_mfg ON project_parts(mechanical_manufacture_id);
CREATE INDEX IF NOT EXISTS idx_project_parts_mech_bop ON project_parts(mechanical_bought_out_part_id);
CREATE INDEX IF NOT EXISTS idx_project_parts_elec_mfg ON project_parts(electrical_manufacture_id);
CREATE INDEX IF NOT EXISTS idx_project_parts_elec_bop ON project_parts(electrical_bought_out_part_id);
CREATE INDEX IF NOT EXISTS idx_project_parts_pneu_bop ON project_parts(pneumatic_bought_out_part_id);

-- --------------------------------------------------------
-- purchase_orders
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS purchase_orders (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  po_number       TEXT NOT NULL UNIQUE,
  project_id      BIGINT NOT NULL REFERENCES projects(id),
  supplier_id     BIGINT NOT NULL REFERENCES suppliers(id),
  po_date         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  status          TEXT NOT NULL DEFAULT 'Pending'
                    CHECK (status IN ('Pending','Sent','Confirmed','Partial','Received','Cancelled')),
  currency        TEXT NOT NULL DEFAULT 'INR',
  grand_total     NUMERIC(18, 2) NOT NULL DEFAULT 0,
  total_items     INT NOT NULL DEFAULT 0,
  total_quantity  INT NOT NULL DEFAULT 0,
  notes           TEXT,
  terms           TEXT,
  created_date    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_date    TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_po_number  ON purchase_orders(po_number);
CREATE INDEX IF NOT EXISTS idx_po_project ON purchase_orders(project_id);
CREATE INDEX IF NOT EXISTS idx_po_supplier ON purchase_orders(supplier_id);

-- --------------------------------------------------------
-- purchase_order_items
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS purchase_order_items (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  purchase_order_id   BIGINT NOT NULL REFERENCES purchase_orders(id) ON DELETE CASCADE,
  part_type           TEXT NOT NULL,
  part_number         TEXT NOT NULL,
  description         TEXT,
  quantity            INT NOT NULL DEFAULT 0,
  unit_price          NUMERIC(18, 2) NOT NULL DEFAULT 0,
  discount_percent    NUMERIC(5, 2) NOT NULL DEFAULT 0,
  total_amount        NUMERIC(18, 2) NOT NULL DEFAULT 0,
  project_part_id     BIGINT REFERENCES project_parts(id)
);

CREATE INDEX IF NOT EXISTS idx_poi_order ON purchase_order_items(purchase_order_id);

-- --------------------------------------------------------
-- part_usage_logs
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS part_usage_logs (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_name     TEXT NOT NULL,
  site_name        TEXT,
  use_date_time    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  part_number      TEXT NOT NULL,
  part_table_name  TEXT NOT NULL,
  quantity         INT NOT NULL DEFAULT 0,
  created_date     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_pul_part_number ON part_usage_logs(part_number);

-- --------------------------------------------------------
-- json_excel_file_uploaded
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS json_excel_file_uploaded (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_name           TEXT,
  date_time           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  json_content_type   TEXT,
  json_data           TEXT,
  excel_path          TEXT,   -- Supabase Storage path
  parts_processed     INT NOT NULL DEFAULT 0,
  parts_added         INT NOT NULL DEFAULT 0,
  parts_updated       INT NOT NULL DEFAULT 0,
  errors              INT NOT NULL DEFAULT 0,
  error_message       TEXT
);


-- ================================================================
-- PART 2: ROW LEVEL SECURITY — Authenticated users only
-- ================================================================

-- Enable RLS on every table
ALTER TABLE suppliers                ENABLE ROW LEVEL SECURITY;
ALTER TABLE projects                 ENABLE ROW LEVEL SECURITY;
ALTER TABLE project_sections         ENABLE ROW LEVEL SECURITY;
ALTER TABLE mechanical_manufacture   ENABLE ROW LEVEL SECURITY;
ALTER TABLE mechanical_bought_out    ENABLE ROW LEVEL SECURITY;
ALTER TABLE electrical_manufacture   ENABLE ROW LEVEL SECURITY;
ALTER TABLE electrical_bought_out    ENABLE ROW LEVEL SECURITY;
ALTER TABLE pneumatic_bought_out     ENABLE ROW LEVEL SECURITY;
ALTER TABLE project_parts            ENABLE ROW LEVEL SECURITY;
ALTER TABLE purchase_orders          ENABLE ROW LEVEL SECURITY;
ALTER TABLE purchase_order_items     ENABLE ROW LEVEL SECURITY;
ALTER TABLE part_usage_logs          ENABLE ROW LEVEL SECURITY;
ALTER TABLE json_excel_file_uploaded ENABLE ROW LEVEL SECURITY;

-- RLS Policies: Only authenticated users can do anything
CREATE POLICY "auth_all" ON suppliers
  FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "auth_all" ON projects
  FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "auth_all" ON project_sections
  FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "auth_all" ON mechanical_manufacture
  FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "auth_all" ON mechanical_bought_out
  FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "auth_all" ON electrical_manufacture
  FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "auth_all" ON electrical_bought_out
  FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "auth_all" ON pneumatic_bought_out
  FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "auth_all" ON project_parts
  FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "auth_all" ON purchase_orders
  FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "auth_all" ON purchase_order_items
  FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "auth_all" ON part_usage_logs
  FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "auth_all" ON json_excel_file_uploaded
  FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');


-- ================================================================
-- PART 3: STORAGE — "drawings" bucket policies
-- NOTE: Create the bucket manually in the Supabase Dashboard:
--   Storage → New Bucket → Name: drawings → Public: OFF
-- Then run the policies below.
-- ================================================================

CREATE POLICY "drawings_insert" ON storage.objects
  FOR INSERT WITH CHECK (
    bucket_id = 'drawings' AND auth.role() = 'authenticated'
  );

CREATE POLICY "drawings_select" ON storage.objects
  FOR SELECT USING (
    bucket_id = 'drawings' AND auth.role() = 'authenticated'
  );

CREATE POLICY "drawings_update" ON storage.objects
  FOR UPDATE USING (
    bucket_id = 'drawings' AND auth.role() = 'authenticated'
  );

CREATE POLICY "drawings_delete" ON storage.objects
  FOR DELETE USING (
    bucket_id = 'drawings' AND auth.role() = 'authenticated'
  );


-- ================================================================
-- PART 4: DATABASE FUNCTIONS
-- ================================================================

-- Dashboard stats — called via supabase.rpc('get_dashboard_stats')
CREATE OR REPLACE FUNCTION get_dashboard_stats()
RETURNS JSON
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  result JSON;
BEGIN
  SELECT json_build_object(
    'total_parts', (
      (SELECT COUNT(*) FROM mechanical_manufacture) +
      (SELECT COUNT(*) FROM mechanical_bought_out)  +
      (SELECT COUNT(*) FROM electrical_manufacture) +
      (SELECT COUNT(*) FROM electrical_bought_out)  +
      (SELECT COUNT(*) FROM pneumatic_bought_out)
    ),
    'mechanical_manufacture', (SELECT COUNT(*) FROM mechanical_manufacture),
    'mechanical_bought_out',  (SELECT COUNT(*) FROM mechanical_bought_out),
    'electrical_manufacture', (SELECT COUNT(*) FROM electrical_manufacture),
    'electrical_bought_out',  (SELECT COUNT(*) FROM electrical_bought_out),
    'pneumatic_bought_out',   (SELECT COUNT(*) FROM pneumatic_bought_out),
    'low_stock_alerts', (
      (SELECT COUNT(*) FROM mechanical_manufacture WHERE stock_quantity < min_stock_level AND min_stock_level > 0) +
      (SELECT COUNT(*) FROM mechanical_bought_out  WHERE stock_quantity < min_stock_level AND min_stock_level > 0) +
      (SELECT COUNT(*) FROM electrical_manufacture WHERE stock_quantity < min_stock_level AND min_stock_level > 0) +
      (SELECT COUNT(*) FROM electrical_bought_out  WHERE stock_quantity < min_stock_level AND min_stock_level > 0) +
      (SELECT COUNT(*) FROM pneumatic_bought_out   WHERE stock_quantity < min_stock_level AND min_stock_level > 0)
    ),
    'total_projects',     (SELECT COUNT(*) FROM projects),
    'active_projects',    (SELECT COUNT(*) FROM projects WHERE status NOT IN ('completed','cancelled','on_hold')),
    'completed_projects', (SELECT COUNT(*) FROM projects WHERE status = 'completed'),
    'on_hold_projects',   (SELECT COUNT(*) FROM projects WHERE status = 'on_hold'),
    'total_suppliers',    (SELECT COUNT(*) FROM suppliers),
    'pending_pos',        (SELECT COUNT(*) FROM purchase_orders WHERE status = 'Pending'),
    'total_pos',          (SELECT COUNT(*) FROM purchase_orders)
  ) INTO result;

  RETURN result;
END;
$$;


-- ================================================================
-- PART 5: REALTIME — Enable for live dashboard updates
-- ================================================================

-- Run these to enable realtime for critical tables
ALTER PUBLICATION supabase_realtime ADD TABLE mechanical_manufacture;
ALTER PUBLICATION supabase_realtime ADD TABLE mechanical_bought_out;
ALTER PUBLICATION supabase_realtime ADD TABLE electrical_manufacture;
ALTER PUBLICATION supabase_realtime ADD TABLE electrical_bought_out;
ALTER PUBLICATION supabase_realtime ADD TABLE pneumatic_bought_out;
ALTER PUBLICATION supabase_realtime ADD TABLE projects;
ALTER PUBLICATION supabase_realtime ADD TABLE purchase_orders;


-- ================================================================
-- PART 6: SEED DATA (Optional — remove if not needed)
-- ================================================================

INSERT INTO suppliers (name, contact_person, email, phone, address, payment_terms) VALUES
  ('DigiKey Electronics',  'John Smith',    'john@digikey.com',           '1-800-344-4539', '701 Brooks Ave South, Thief River Falls, MN 56701', 'Net 30'),
  ('Mouser Electronics',   'Sarah Johnson', 'sarah@mouser.com',           '1-800-346-6873', '1000 N Main St, Mansfield, TX 76063',               'Net 30'),
  ('McMaster-Carr',        'Mike Wilson',   'mike@mcmaster.com',          '1-630-833-9600', '200 Aurora Rd, Elmhurst, IL 60126',                  'Net 30'),
  ('AutomationDirect',     'Lisa Brown',    'lisa@automationdirect.com',  '1-800-633-0405', '3505 Hutchinson Rd, Cumming, GA 30040',               'Net 30'),
  ('Parker Hannifin',      'David Lee',     'david@parker.com',           '1-800-272-7537', '6035 Parkland Blvd, Cleveland, OH 44124',             'Net 45')
ON CONFLICT DO NOTHING;

INSERT INTO projects (
  project_name, project_number, customer, description, status,
  start_date, target_completion_date,
  mechanical_design_status, ee_design_status, pneumatic_design_status,
  po_release_status, part_arrival_status, machine_build_status
) VALUES
  ('Automated Dispensing System', 'PRJ-2024-001', 'Acme Corp',   'Liquid dispensing system for automotive parts', 'design',    NOW() - INTERVAL '2 months', NOW() + INTERVAL '4 months', 'in_progress', 'completed',    'not_started', 'not_started', 'not_started', 'not_started'),
  ('PCB Assembly Line',           'PRJ-2024-002', 'TechFlow Inc','Automated PCB assembly and testing',            'planning',  NOW() - INTERVAL '1 month',  NOW() + INTERVAL '6 months', 'not_started', 'not_started',  'not_started', 'not_started', 'not_started', 'not_started'),
  ('CNC Router Upgrade',          'PRJ-2024-003', 'Internal',    'Upgrade CNC router with new control system',   'build',     NOW() - INTERVAL '3 months', NOW() + INTERVAL '1 month',  'completed',   'completed',    'completed',   'completed',   'completed',   'in_progress'),
  ('Robotic Arm Prototype',       'PRJ-2024-004', 'RoboTech',    '6-DOF robotic arm for educational purposes',  'completed', NOW() - INTERVAL '6 months', NOW() - INTERVAL '1 month',  'completed',   'completed',    'completed',   'completed',   'completed',   'completed'),
  ('Conveyor System',             'PRJ-2024-005', 'LogiMove',    'Modular conveyor system for warehouse',        'on_hold',   NOW() - INTERVAL '4 months', NOW() + INTERVAL '2 months', 'completed',   'completed',    'not_started', 'not_started', 'not_started', 'not_started')
ON CONFLICT DO NOTHING;

-- ================================================================
-- DONE  ✓
-- Verify in Supabase: Table Editor should now show 13 tables.
-- ================================================================
