-- 20260711_add_issues.sql
-- Dedicated issue tracking for projects, purchase orders, and parts.
-- Issues are linkable to a project, a PO, and/or a specific project part.
-- This version intentionally avoids DO $$ blocks because the Supabase SQL editor
-- can be finicky with dollar-quoted procedural blocks.

CREATE TABLE IF NOT EXISTS public.issues (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  project_id BIGINT REFERENCES public.projects(id) ON DELETE CASCADE,
  purchase_order_id BIGINT REFERENCES public.purchase_orders(id) ON DELETE SET NULL,
  project_part_id BIGINT REFERENCES public.project_parts(id) ON DELETE SET NULL,
  title TEXT NOT NULL,
  description TEXT,
  category TEXT NOT NULL DEFAULT 'other',
  severity TEXT NOT NULL DEFAULT 'medium',
  status TEXT NOT NULL DEFAULT 'open',
  assigned_to UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  due_date DATE,
  resolved_at TIMESTAMPTZ,
  resolved_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  links JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ
);

ALTER TABLE public.issues
  DROP CONSTRAINT IF EXISTS issues_category_check;

ALTER TABLE public.issues
  ADD CONSTRAINT issues_category_check
  CHECK (category IN ('delivery', 'quality', 'design', 'supplier', 'commercial', 'other'));

ALTER TABLE public.issues
  DROP CONSTRAINT IF EXISTS issues_severity_check;

ALTER TABLE public.issues
  ADD CONSTRAINT issues_severity_check
  CHECK (severity IN ('low', 'medium', 'high', 'critical'));

ALTER TABLE public.issues
  DROP CONSTRAINT IF EXISTS issues_status_check;

ALTER TABLE public.issues
  ADD CONSTRAINT issues_status_check
  CHECK (status IN ('open', 'in_progress', 'resolved', 'closed'));

CREATE INDEX IF NOT EXISTS idx_issues_project_id
  ON public.issues(project_id);

CREATE INDEX IF NOT EXISTS idx_issues_purchase_order_id
  ON public.issues(purchase_order_id);

CREATE INDEX IF NOT EXISTS idx_issues_status
  ON public.issues(status);

CREATE TABLE IF NOT EXISTS public.issue_comments (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  issue_id BIGINT NOT NULL REFERENCES public.issues(id) ON DELETE CASCADE,
  user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  comment_text TEXT NOT NULL,
  images JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_issue_comments_issue
  ON public.issue_comments(issue_id, created_at DESC);

ALTER TABLE public.issues ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.issue_comments ENABLE ROW LEVEL SECURITY;

-- RLS keeps parity with other tracking tables: any authenticated user can read
-- and write; admin-only actions (delete) are enforced in the app layer.

DROP POLICY IF EXISTS "Issues are viewable by authenticated users"
  ON public.issues;

CREATE POLICY "Issues are viewable by authenticated users"
  ON public.issues FOR SELECT
  TO authenticated
  USING (true);

DROP POLICY IF EXISTS "Authenticated users can create issues"
  ON public.issues;

CREATE POLICY "Authenticated users can create issues"
  ON public.issues FOR INSERT
  TO authenticated
  WITH CHECK (true);

DROP POLICY IF EXISTS "Authenticated users can update issues"
  ON public.issues;

CREATE POLICY "Authenticated users can update issues"
  ON public.issues FOR UPDATE
  TO authenticated
  USING (true)
  WITH CHECK (true);

DROP POLICY IF EXISTS "Authenticated users can delete issues"
  ON public.issues;

CREATE POLICY "Authenticated users can delete issues"
  ON public.issues FOR DELETE
  TO authenticated
  USING (true);

DROP POLICY IF EXISTS "Issue comments are viewable by authenticated users"
  ON public.issue_comments;

CREATE POLICY "Issue comments are viewable by authenticated users"
  ON public.issue_comments FOR SELECT
  TO authenticated
  USING (true);

DROP POLICY IF EXISTS "Authenticated users can insert issue comments"
  ON public.issue_comments;

CREATE POLICY "Authenticated users can insert issue comments"
  ON public.issue_comments FOR INSERT
  TO authenticated
  WITH CHECK (true);
