-- 20260605_project_tracking_foundation.sql
-- Phase 1 foundation for project tracking, supplier ownership, and progress updates.
-- This version intentionally avoids DO $$ blocks because the Supabase SQL editor
-- can be finicky with dollar-quoted procedural blocks.

ALTER TABLE public.pending_parts
  ADD COLUMN IF NOT EXISTS section_id BIGINT REFERENCES public.project_sections(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS subsection_id BIGINT REFERENCES public.project_subsections(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS supplier_id BIGINT REFERENCES public.suppliers(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS due_date DATE,
  ADD COLUMN IF NOT EXISTS target_date DATE,
  ADD COLUMN IF NOT EXISTS next_action TEXT,
  ADD COLUMN IF NOT EXISTS blocker TEXT,
  ADD COLUMN IF NOT EXISTS progress_percent INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS tracking_status TEXT,
  ADD COLUMN IF NOT EXISTS risk_level TEXT NOT NULL DEFAULT 'normal';

ALTER TABLE public.pending_parts
  DROP CONSTRAINT IF EXISTS pending_parts_progress_percent_check;

ALTER TABLE public.pending_parts
  ADD CONSTRAINT pending_parts_progress_percent_check
  CHECK (progress_percent >= 0 AND progress_percent <= 100);

ALTER TABLE public.pending_parts
  DROP CONSTRAINT IF EXISTS pending_parts_risk_level_check;

ALTER TABLE public.pending_parts
  ADD CONSTRAINT pending_parts_risk_level_check
  CHECK (risk_level IN ('low', 'normal', 'high', 'critical'));

CREATE INDEX IF NOT EXISTS idx_pending_parts_supplier_id
  ON public.pending_parts(supplier_id);

CREATE INDEX IF NOT EXISTS idx_pending_parts_due_date
  ON public.pending_parts(due_date);

CREATE INDEX IF NOT EXISTS idx_pending_parts_section_context
  ON public.pending_parts(project_id, section_id, subsection_id);

CREATE TABLE IF NOT EXISTS public.supplier_assignments (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  project_id BIGINT NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
  supplier_id BIGINT NOT NULL REFERENCES public.suppliers(id) ON DELETE CASCADE,
  section_id BIGINT REFERENCES public.project_sections(id) ON DELETE SET NULL,
  subsection_id BIGINT REFERENCES public.project_subsections(id) ON DELETE SET NULL,
  work_item_id BIGINT REFERENCES public.pending_parts(id) ON DELETE SET NULL,
  assigned_user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  current_status TEXT NOT NULL DEFAULT 'not_started',
  target_date DATE,
  remarks TEXT,
  last_updated_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  last_updated_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_supplier_assignments_project
  ON public.supplier_assignments(project_id);

CREATE INDEX IF NOT EXISTS idx_supplier_assignments_supplier
  ON public.supplier_assignments(supplier_id);

CREATE INDEX IF NOT EXISTS idx_supplier_assignments_assigned_user
  ON public.supplier_assignments(assigned_user_id);

CREATE INDEX IF NOT EXISTS idx_supplier_assignments_target_date
  ON public.supplier_assignments(target_date);

CREATE TABLE IF NOT EXISTS public.work_item_updates (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  work_item_id BIGINT NOT NULL REFERENCES public.pending_parts(id) ON DELETE CASCADE,
  user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  update_text TEXT NOT NULL,
  status TEXT,
  progress_percent INT,
  blocker TEXT,
  next_step TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.work_item_updates
  DROP CONSTRAINT IF EXISTS work_item_updates_progress_percent_check;

ALTER TABLE public.work_item_updates
  ADD CONSTRAINT work_item_updates_progress_percent_check
  CHECK (progress_percent IS NULL OR (progress_percent >= 0 AND progress_percent <= 100));

CREATE INDEX IF NOT EXISTS idx_work_item_updates_work_item
  ON public.work_item_updates(work_item_id, created_at DESC);

ALTER TABLE public.supplier_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.work_item_updates ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Supplier assignments are viewable by authenticated users"
  ON public.supplier_assignments;

CREATE POLICY "Supplier assignments are viewable by authenticated users"
  ON public.supplier_assignments FOR SELECT
  TO authenticated
  USING (true);

DROP POLICY IF EXISTS "Authenticated users can create supplier assignments"
  ON public.supplier_assignments;

CREATE POLICY "Authenticated users can create supplier assignments"
  ON public.supplier_assignments FOR INSERT
  TO authenticated
  WITH CHECK (true);

DROP POLICY IF EXISTS "Authenticated users can update supplier assignments"
  ON public.supplier_assignments;

CREATE POLICY "Authenticated users can update supplier assignments"
  ON public.supplier_assignments FOR UPDATE
  TO authenticated
  USING (true)
  WITH CHECK (true);

DROP POLICY IF EXISTS "Work item updates are viewable by authenticated users"
  ON public.work_item_updates;

CREATE POLICY "Work item updates are viewable by authenticated users"
  ON public.work_item_updates FOR SELECT
  TO authenticated
  USING (true);

DROP POLICY IF EXISTS "Authenticated users can insert work item updates"
  ON public.work_item_updates;

CREATE POLICY "Authenticated users can insert work item updates"
  ON public.work_item_updates FOR INSERT
  TO authenticated
  WITH CHECK (true);
