-- 20260427_add_pending_parts.sql
-- Migration: Add Pending Parts Feature (Task 2)

CREATE TABLE IF NOT EXISTS public.pending_parts (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    project_id BIGINT NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    description TEXT,
    category TEXT,
    status TEXT NOT NULL DEFAULT 'Pending', -- 'Pending', 'Approved', 'Rejected'
    created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    images JSONB DEFAULT '[]'::jsonb,
    links JSONB DEFAULT '[]'::jsonb,
    rejection_reason TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS public.pending_part_comments (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    pending_part_id BIGINT NOT NULL REFERENCES public.pending_parts(id) ON DELETE CASCADE,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    message TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- RLS Policies for pending_parts
ALTER TABLE public.pending_parts ENABLE ROW LEVEL SECURITY;

-- 1. Everyone authenticated can read
CREATE POLICY "Pending parts are viewable by authenticated users"
ON public.pending_parts FOR SELECT
TO authenticated
USING (true);

-- 2. Everyone authenticated can insert
CREATE POLICY "Authenticated users can create pending parts"
ON public.pending_parts FOR INSERT
TO authenticated
WITH CHECK (true);

-- 3. Authenticated users can update. 
-- NOTE: We allow authenticated users to update here as a baseline, 
-- but strictly enforce the "Admin Only" approval/rejection logic in the UI/API.
CREATE POLICY "Authenticated users can update pending parts"
ON public.pending_parts FOR UPDATE
TO authenticated
USING (true)
WITH CHECK (true);


-- RLS Policies for pending_part_comments
ALTER TABLE public.pending_part_comments ENABLE ROW LEVEL SECURITY;

-- 1. Comments are viewable by authenticated users
CREATE POLICY "Comments are viewable by authenticated users"
ON public.pending_part_comments FOR SELECT
TO authenticated
USING (true);

-- 2. Authenticated users can insert comments
CREATE POLICY "Authenticated users can insert comments"
ON public.pending_part_comments FOR INSERT
TO authenticated
WITH CHECK (true);
